#!/usr/bin/env bash
# Sentinal — Sumo Logic Health Check (OpenClaw distribution)
# Usage: bash sumo-health.sh [ACCESS_ID] [ACCESS_KEY] [REGION]
# Or set SUMO_ACCESS_ID, SUMO_ACCESS_KEY, SUMO_REGION env vars

set -euo pipefail

ACCESS_ID="${1:-${SUMO_ACCESS_ID:-}}"
ACCESS_KEY="${2:-${SUMO_ACCESS_KEY:-}}"
REGION="${3:-${SUMO_REGION:-us1}}"

if [ -z "$ACCESS_ID" ] || [ -z "$ACCESS_KEY" ]; then
    echo "Error: Sumo Logic credentials required."
    echo "Usage: bash sumo-health.sh <ACCESS_ID> <ACCESS_KEY> [REGION]"
    echo "   Or: SUMO_ACCESS_ID=... SUMO_ACCESS_KEY=... bash sumo-health.sh"
    exit 1
fi

# Region to base URL
declare -A REGIONS=(
    [us1]="https://api.sumologic.com/api"
    [us2]="https://api.us2.sumologic.com/api"
    [eu]="https://api.eu.sumologic.com/api"
    [au]="https://api.au.sumologic.com/api"
    [de]="https://api.de.sumologic.com/api"
    [jp]="https://api.jp.sumologic.com/api"
    [ca]="https://api.ca.sumologic.com/api"
    [in]="https://api.in.sumologic.com/api"
    [fed]="https://api.fed.sumologic.com/api"
)

BASE_URL="${REGIONS[$REGION]:-}"
if [ -z "$BASE_URL" ]; then
    echo "Error: Unknown region '$REGION'. Valid: ${!REGIONS[*]}"
    exit 1
fi

# Mask credentials for display
SAFE_ID="${ACCESS_ID:0:4}****${ACCESS_ID: -2}"

# Auth header
AUTH=$(echo -n "$ACCESS_ID:$ACCESS_KEY" | base64)

sumo_curl() {
    curl -s -H "Authorization: Basic $AUTH" -H "Content-Type: application/json" "$BASE_URL$1"
}

divider() { echo "────────────────────────────────────────"; }
header() { echo ""; divider; echo "  $1"; divider; }
warn() { echo "  ⚠ WARNING: $1"; }
ok() { echo "  ✓ $1"; }

echo ""
echo "╔════════════════════════════════════════╗"
echo "║  Sentinal Sumo Logic Health Report     ║"
echo "╚════════════════════════════════════════╝"
echo "  Region: $REGION"
echo "  Auth:   $SAFE_ID"
echo "  Time:   $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

# Connectivity
header "CONNECTIVITY"
ping_response=$(sumo_curl "/v1/collectors?limit=1" 2>/dev/null) || true
if echo "$ping_response" | jq -e '.collectors' >/dev/null 2>&1; then
    ok "Sumo Logic API is reachable, auth valid"
else
    echo "  ✗ CRITICAL: Cannot connect to Sumo Logic"
    echo "  Response: $(echo "$ping_response" | head -c 200)"
    exit 1
fi

# Collectors
header "COLLECTORS"
collectors_json=$(sumo_curl "/v1/collectors?limit=200" 2>/dev/null) || true
total=$(echo "$collectors_json" | jq '.collectors | length' 2>/dev/null || echo 0)
alive=$(echo "$collectors_json" | jq '[.collectors[] | select(.alive == true)] | length' 2>/dev/null || echo 0)
dead=$(echo "$collectors_json" | jq '[.collectors[] | select(.alive == false)] | length' 2>/dev/null || echo 0)

echo "  Total:  $total"
echo "  Alive:  $alive"
echo "  Dead:   $dead"

if [ "$dead" -gt 0 ] 2>/dev/null; then
    warn "$dead collector(s) are offline:"
    echo "$collectors_json" | jq -r '.collectors[] | select(.alive == false) | "    - \(.name) (\(.collectorType))"' 2>/dev/null | head -10
fi

# Monitors
header "MONITORS"
monitors_json=$(sumo_curl "/v1/monitors/search?query=status:Critical%20OR%20status:Warning&limit=20" 2>/dev/null) || true
triggered=$(echo "$monitors_json" | jq '.data | length' 2>/dev/null || echo 0)

if [ "$triggered" -eq 0 ] 2>/dev/null; then
    ok "No monitors in Critical or Warning state"
else
    critical=$(echo "$monitors_json" | jq '[.data[] | select(.status == "Critical")] | length' 2>/dev/null || echo 0)
    warning=$(echo "$monitors_json" | jq '[.data[] | select(.status == "Warning")] | length' 2>/dev/null || echo 0)
    [ "$critical" -gt 0 ] && warn "CRITICAL: $critical monitor(s)"
    [ "$warning" -gt 0 ] && warn "WARNING: $warning monitor(s)"
    echo "$monitors_json" | jq -r '.data[] | "    - [\(.status)] \(.name)"' 2>/dev/null | head -10
fi

# Summary
header "SUMMARY"
if [ "$dead" -gt 0 ] 2>/dev/null; then
    warn "$dead dead collector(s) need attention"
else
    ok "All collectors online"
fi
if [ "$triggered" -gt 0 ] 2>/dev/null; then
    warn "$triggered monitor(s) alerting"
else
    ok "No active alerts"
fi

echo ""
echo "Report generated by Sentinal v1.1.0"
echo ""
